name: ipoanki
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  flutter_modular: 5.0.3
  animated_text_kit: 4.2.2
  google_fonts: 4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.12.0
  flutter_lints: 2.0.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Guy
      fonts:
        - asset: assets/fonts/guy/LuckiestGuy-Regular.ttf
