name: Merge PR on Approval
on:
  pull_request_review:
    types:
      - submitted

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge Pull Request
        run: |
          if [ ${{ github.event.review.state }} == 'approved' ]; then
            echo "PR has been approved. Merging..."
            gh pr merge --auto
          else
            echo "PR has not been approved. Skipping merge."
          fi
